comment:
  layout: "header, diff, tree"

coverage:
  range: "70...100"
  precision: 2
  round: down
  status:
    patch: false
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 5%
