# Copyright 2020 The SODA Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: check for SRM Toolchain files existed
  stat:
    path: "{{ srm_toolchain_work_dir }}"
  register: srmtoolchainexisted

- name: Stop and remove Prometheus, Alertmanager, Grafana containers but don't delete the images
  shell: docker compose rm -fs
  args:
    chdir: "{{ srm_toolchain_work_dir }}/"
  when:
    - source_purge == false
    - srmtoolchainexisted.stat.isdir is defined and srmtoolchainexisted.stat.isdir

- name: Stop and remove Prometheus, Alertmanager, Grafana containers & delete the images
  shell: docker compose down --rmi all
  args:
    chdir: "{{ srm_toolchain_work_dir }}/"
  when:
    - source_purge is undefined or source_purge != false
    - srmtoolchainexisted.stat.isdir is defined and srmtoolchainexisted.stat.isdir

- name: clean up all SRM Toolchain directories
  file:
    path: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - "{{ srm_toolchain_work_dir }}/"
  ignore_errors: yes
  tags:
    - srm_toolchain
    - clean
  when:
    - source_purge is undefined or source_purge != false
    - srmtoolchainexisted.stat.isdir is defined and srmtoolchainexisted.stat.isdir
    
