{
 "title": "Performance Monitor - Overall Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "delfin_storage_id", "label": "Delfin Storage ID", "query": "label_values(storage_id)" },
   { "name": "resource_type", "label": "Resource Type", "query": "label_values(resource_type)" },
   {
    "name": "resource_id",
    "label": "Resource ID",
    "query": "label_values({resource_type=\"$resource_type\"}, resource_id)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average IOPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(${resource_type}_iops{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"})"
    }
   ]
  },
  {
   "title": "Average Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(${resource_type}_throughput{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"})"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(${resource_type}_responseTime{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"})"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "${resource_id} Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_responseTime{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "${resource_id} Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_throughput{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  {
   "title": "${resource_id} Read Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_readThroughput{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  {
   "title": "${resource_id} Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_writeThroughput{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "${resource_id} IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_iops{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  {
   "title": "${resource_id} Read IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_readIops{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  {
   "title": "${resource_id} Write IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_writeIops{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  { "title": "IO Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "${resource_id} IO Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_ioSize{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  {
   "title": "${resource_id} Read IO Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_readIoSize{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  {
   "title": "${resource_id} Write IO Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_writeIoSize{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  { "title": "Cache Hit Ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "${resource_id} Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_cacheHitRatio{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  {
   "title": "${resource_id} Read Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_readCacheHitRatio{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  },
  {
   "title": "${resource_id} Write Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "${resource_type}_writeCacheHitRatio{storage_id=\"${delfin_storage_id}\", resource_id=\"${resource_id}\"}",
     "legendFormat": "${resource_id}"
    }
   ]
  }
 ]
}