#!/bin/bash
# Copyright 2020 The SODA Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PYTHON='python3'
BASEDIR=$(dirname "$0")


delfin_install_usage(){
    echo "Usage $(basename $0) [--help|--precheck|--skip_precheck]"
cat << DELFIN_INSTALL_INFO
Usage:
    $(basename $0) [-h|--help]
    $(basename $0) [-p|--precheck]
    $(basename $0) [-s|--skip_precheck]
Flags:
    -h, --help Print the usage of install
    -p, --precheck Only perform system software requirements for installation
    -s, --skip_precheck If precheck is not required and directly install
DELFIN_INSTALL_INFO
}

precheck(){
    delfin::log "Precheck called.."
    echo $!
    source ${BASEDIR}/precheck
}

precheck_and_install(){
    delfin::log "precheck_and_install"
    precheck
    install
}


install(){
    delfin::log "Install called.."

    ${PYTHON} ${BASEDIR}/install_delfin.py
}

main(){
    
    first_arg=${1}
    second_arg=${2}
    source ${BASEDIR}/util.sh

    echo "${PROJECT_NAME} installation started... "
    case "${first_arg} ${second_arg}" in
    "1 -p"|"1 --precheck")
        precheck
        ;;
    "0 ")
        precheck_and_install
        ;;
    "1 -s"|"1 --skip_precheck")
        install
        ;;
    *)
        delfin_install_usage
        exit 1
        ;;
    esac
}

# Entry point. START
args="$# $*"

main ${args}
